---
- name: Install Nginx and PHP-FPM
  hosts: web_servers
  become: true

  vars:
    domain_name: test.local
    enable_https: true
    server_name: test.loac
    generate_ssl_certs: true
    php_version: 8.2

    max_children: 10
    start_servers: 3
    min_spare_servers: 2
    max_spare_servers: 5
    max_requests: 500

  roles:
    - name: nginx-role
    - name: php-fpm-role

  tasks:
    - name: Test the domain using cURL
      uri:
        url: "http://{{ domain_name }}/info.php"
      register: curl_result
      until: curl_result is success
      retries: 10
      delay: 5

    - name: Display cURL result
      debug:
        var: curl_result
